Add more missing words
Summary:
spec generation script still failing with
Error: cannot decode endpoint space_participants in class Page

https://www.internalfb.com/chronos/job_instance/gp/27021602565366776/simple-logs

Reviewed By: liliarizona

Differential Revision: D90654080

fbshipit-source-id: db939bc022e348f46720fb0d25025f398c9c5b36