Revert D82676861
Summary:
reverting D82676861 as the codegen is broken
https://www.internalfb.com/chronos/job_instance/gp/27021602360097521/simple-logs

Err: Error: Cannot find module 'merge'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/facebook/bumblebee/1570371573045235068_27021602360097521/business-sdk/codegen/lib/processors/CodeGenNameConventions.js:16:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

will be addressing vulnerability issue later...

Differential Revision: D83201868

fbshipit-source-id: db523edb9a4d461d81f66021fd426bf27cc99933